v1.0.3 (#4)
Major updates
* Using latest 14.0 build
* Adding individual database backups

diff --git a/overlay/usr/lib/bf/postgresql/backup b/overlay/usr/lib/bf/postgresql/backup
--- a/overlay/usr/lib/bf/postgresql/backup
+++ b/overlay/usr/lib/bf/postgresql/backup
@@ -26,14 +26,42 @@ bf-echo "Backing up server to ${TEMP_BACKUP_PATH}..."
 
 # dump cluster
 DUMP_FILE="${TEMP_BACKUP_PATH}/${POSTGRESQL_BACKUP_FILENAME}.sql"
-bf-debug " .. dumping cluster to ${DUMP_FILE}"
+bf-debug " .. dumping cluster"
 pg_dumpall > "${DUMP_FILE}"
 
 # compress file
 if [ "${POSTGRESQL_BACKUP_COMPRESS_FILES}" = "1" ] ; then
-    bf-debug " .. compressing cluster backup"
+    bf-debug " .. compressing"
     gzip ${DUMP_FILE}
 fi
+
+
+#======================================================================================================================
+# Get list of individual databases, dump and compress.
+#======================================================================================================================
+
+# remove header / footer from output
+EXCLUDE="postgres|template0|template1"
+bf-debug " .. excluding ${EXCLUDE} from individual backups"
+DATABASES=$(psql -c "SELECT datname FROM pg_database;" | tail -n+3 | head -n-2 | grep -v -E "(${EXCLUDE})")
+
+# dump each database
+for DATABASE in ${DATABASES} ; do
+
+    # path to this database dump
+    DUMP_FILE="${TEMP_BACKUP_PATH}/${DATABASE}.sql"
+
+    # dump database and continue on failure
+    bf-debug " .. dumping database ${DATABASE}"
+    pg_dump ${DATABASE} > ${DUMP_FILE}|| true
+
+    # compress file
+    if [ "${POSTGRESQL_BACKUP_COMPRESS_FILES}" = "1" ] ; then
+        bf-debug " .. compressing"
+        gzip ${DUMP_FILE}
+    fi
+
+done
 
 bf-done
 
